import { createTheme, ThemeProvider } from '@mui/material/styles'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Intro from '../components/Intro'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const theme = createTheme({
    palette: {
      primary: {
        main: '#217BF4',
      },
    },
  });
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Social Piggies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Intro />
    </ThemeProvider >
  )
}

export default Home
